# Doctrine configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: "%db_host%"
        port: "%db_port%"
        dbname: "%db_name%"
        user: "%db_user%"
        password: "%db_pass%"
        charset: UTF8
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true