# FOS configurations
fos_rest:
    view:
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']
        view_response_listener: force
        formats:
            json: true
            xml: true
        templating_formats:
            html: true
        exception_wrapper_handler:  null
        failed_validation: HTTP_BAD_REQUEST

    format_listener:
        rules:
            - { path: '^/c/%kernel.environment%/api', priorities: [ 'json', 'xml' ], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: [ 'html', '*/*' ], fallback_format: html, prefer_extension: true }
        media_type:
            version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'

    exception:
        enabled: true
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': true
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': true
            'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException': true

    param_fetcher_listener: true

    allowed_methods_listener: true

    body_listener: true

    access_denied_listener:
        json: true

    routing_loader:
        default_format: json

    service:
        exception_handler: fos_rest.view.exception_wrapper_handler
